### ISSUE TITLE
Move to cucumber org?

### ISSUE THREAD

**Issue by davidjgoss** [cucumber/cucumber-js-examples#7]
As discussed at the community call today, it’s kinda weird that there’s a separate org on GitHub for these examples.

Maybe there’s a good reason we’ve overlooked?

Otherwise, let’s maybe move it to the cucumber org with everything else.

cc @mattwynne

**Comment by mattwynne** [comment]
Done. Now we need to update the links in the cucumber-js repo.

**Comment by mattwynne** [comment]
Links updated. I'm calling this done.
